baseURL = "https://playordinai.github.io/"
title = "Ordinai"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancytitle = 'Ordinai'
copyright = "John Doe"
description = 'Medieval Fantasy Sandbox'
startbuttonText = "Activate"
startbuttonLink = "https://www.curseforge.com/minecraft/modpacks/ordinai"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = "images/"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Changelogs"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Ignite your senses and feel the experience come alive.'
body = '''
Unleashing its potential, currently in development.
'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "images/background.png"
img_alt = "blurry background: white/grey"
title = 'Enjoy your time with friends'
body = 'Experience the joy of shared adventures as you bask in unforgettable moments with cherished friends.'

[[params.two.section]]
img = "images/background2.png"
title = 'Friendly developers team'
body = 'A friendly developers team fosters a seamless and collaborative process, enhancing the overall development and in-game experience.'

[[params.two.section]]
img = "images/background3.png"
title = 'Convenience via Curseforge'
body = 'Streamline the installation process effortlessly with the convenience of user-friendly Curseforge.'

[params.three]
enable = true
title = 'How We Operate'
body = '''
'''

[[params.three.feature]]
icon = "solid fa-code"
title = "Development"
body = "Ordinai development is driven by core values of authenticity, creativity, player engagement, quality, and inclusivity. The team meticulously integrates historical artifacts, encourages innovative approaches, values community input, delivers polished experiences, and fosters a diverse and inclusive gaming environment. These values shape Ordinai into an immersive and engaging RPG for players to enjoy."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Values"
body = "The developers of Ordinai, hailing from Lithuania, seek to incorporate values such as authenticity, cultural heritage, inclusivity, collaboration, and community engagement into the project. Drawing inspiration from their own heritage, they aim to create an immersive and respectful game experience that celebrates and reflects aspects of Lithuanian history, while also involving players in shaping the game."

[[params.three.feature]]
icon = "fa-heart"
title = "Objective"
body = "The primary objective of Ordinai is to create a captivating RPG experience centered around historical artifacts while continuously optimizing and enhancing the game's progression system."

[[params.three.feature]]
icon = "fa-flag"
title = "Our Team"
body = "Developers: VodeuM, Dudalypas <br /> Artist: Mace <br /> Testers: DSTX"

[params.cta]
enable = true
title = "Changelogs"
body = "Summarizes updates, fixes, enhancements, and changes."

[[params.cta.link]]
href = "/posts/"
text = "learn more"
special = true

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
subject = "New Submission!"
formspree_form_id = "xovaadej"

[params.social]
twitter = ""
mastodon = ""
github = "OrdinaiCo"
discord = "invite/wJWJKXMhNe"
youtube = "@Ordinai"
instagram = ""
curseforge = "https://www.curseforge.com/minecraft/modpacks/ordinai"

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
